### ISSUE TITLE
Cannot add bibliography after ODF-to-citations

### ISSUE THREAD

**Issue by marco-brandizi** [Zotero-ODF-Scan/zotero-odf-scan#26]
I insert scannable cite in my ODF document, then I use the RDF/ODF scan plugin to generate citations via 'ODF to citations', then I open the resulting document with Libre Office and I click 'Add/Edit Bibliography' from the Zotero plugin buttons.

I get the message: 'You must insert a citation before performing this operation.' Which is logically wrong, because the scan plugin has created citations from scannable citations (if not, the documentation isn't very clear).

I'm using:
- Zotero 5.0.55
- RTF/ODF Scan for Zotero 2.0.35
- LibreOffice 6.1.1.2
- macOS 10.13.6 (17G65)

**Comment by adam3smith** [comment]
From the documentation:
> Setting a Citation Style
Now open the converted document — by default it will have (citation) in its file name — in LibreOffice. In the toolbar of the Zotero LibreOffice plugin, **click the Set Document Preferences button and choose a citation style.**

It sounds like you're missing that step. 

> (if not, the documentation isn't very clear).

Possible, though you also didn't read the documentation properly, otherwise you wouldn't have opened a ticket:

> Support
Please ask any questions and report problems to the RTF/ODF - Scan thread on the Zotero forums.

**Comment by marco-brandizi** [comment]
> > Now open the converted document — by default it will have (citation) in its file name — in LibreOffice. In the toolbar of the Zotero LibreOffice plugin, **click the Set Document Preferences button and choose a citation style.**
> 
> It sounds like you're missing that step.
>

Oh, now it works, not exactly intuitive.
 
> Possible, though you also didn't read the documentation properly, otherwise you wouldn't have opened a ticket:
> 

I did read that Zotero issues should go into the forum, but I didn't get that plugin issues should go there too. Honestly, I'm trying to help in a bit confusing situation.
